server:
  http_listen_port: 12345

metrics:
  wal_directory: /tmp/agent/wal
  configs:
    - name: default
      remote_write:
        - url: https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push
          basic_auth:
            username: ${GRAFANA_CLOUD_USERNAME}
            password: ${GRAFANA_CLOUD_PASSWORD}
      scrape_configs:
        - job_name: 'my-node-app'
          static_configs:
            - targets: ['http://devops-project-api-live.internal:3001']
          metrics_path: /metrics
          scrape_interval: 15s